/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_goeswhere_jmh_Exp */

#ifndef _Included_com_goeswhere_jmh_Exp
#define _Included_com_goeswhere_jmh_Exp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_goeswhere_jmh_Exp
 * Method:    calculate
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_com_goeswhere_jmh_Exp_calculate
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     com_goeswhere_jmh_Exp
 * Method:    calculatePointer
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_com_goeswhere_jmh_Exp_calculatePointer
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
